on: [push]

jobs:
  devcontainer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: cgranade/learn-qc-with-python-and-qsharp
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: .devcontainer/Dockerfile
          snapshot: true
